import {
  AlertTriangle,
  ArrowRight,
  ArrowDown,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboard,
  Loader2,
  Moon,
  MoreVertical,
  Package,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  Users,
  X,
  Edit,
  UserPlus,
  PlusCircle,
  Info,
  Calendar,
  Home,
  ChevronsUpDown,
  FileIcon,
  FileImage,
  ArrowLeft,
  LucideLockKeyhole,
  StampIcon,
  Code,
  Cloud,
  Bug,
  IterationCw,
  Mail,
  Youtube,
  type XIcon as LucideIcon,
} from "lucide-react";

export type Icon = typeof LucideIcon;

export const Icons = {
  stamp: StampIcon,
  logo: Command,
  close: X,
  spinner: Loader2,
  calendar: Calendar,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  package: Package,
  dashboard: LayoutDashboard,
  edit: Edit,
  userPlus: UserPlus,
  plusCircle: PlusCircle,
  info: Info,
  home: Home,
  fileIcon: FileIcon,
  fileTextIcon: FileIcon,
  fileImage: FileImage,
  chevronsUpDown: ChevronsUpDown,
  arrowLeft: ArrowLeft,
  lock: LucideLockKeyhole,
  twitter: Twitter,
  check: Check,
  users: Users,
  code: Code,
  deploy: Cloud,
  test: Bug,
  iterate: IterationCw,
  arrowDown: ArrowDown,
  discord: Youtube,
  mail: Mail,
};
